# Generated by Django 4.1.7 on 2023-03-01 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Название"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Категория"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Описание"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.IntegerField(blank=True, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
